robot_name: 'spot_arm'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE", "arm_sh0", "arm_sh1", "arm_el0", "arm_el1", "arm_wr0", "arm_wr1"]
base_name: "base"

state_topic: "spot_arm/state"
command_topic: "spot_arm/command"
change_controller_topic: "spot_arm/change_controller"

contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"]

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.75, -1.6, 0.0, 0.75, -1.6, 0.0, 0.75, -1.6, 0.0, 0.75, -1.6, 0.0, -3.1, 2.1, 0.0, 0.0, 0.0] # LF, LH, RF, RH, arm
  sit_controller:
    joint_angles: [0.0, 1.6, -2.5, 0.0, 1.6, -2.5, 0.0, 1.6, -2.5, 0.0, 1.6, -2.5, 0.0, -3.1, 2.1, 0.0, 0.0, 0.0] # LF, LH, RF, RH, arm
  kp: 500
  kd: 30.0
  interpolation_time: 1.0 # s
  rate: 200 # Hz

mpc_controller:
  wbc_type: "sqp"
  reference_trajectory:
    terrain_topic: "/convex_plane_decomposition_ros/filtered_map"
    reference_topic: "/anymal_mpc_target"
    observation_topic: "/anymal_mpc_observation"
    traj_dt: 0.1
    traj_knots: 10
    blind: true

spot_arm:
  joint_controller:
      type: tbai_ros_gazebo/JointController
      joints: *jn

reference_generator:
  type: "twist"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"

estimator_type: "ground_truth"

gazebo:
  contact_sensor:
    enabled: false
    update_rate: 200 # Hz

  ground_truth_state_publisher:
    enabled: true
    update_rate: 400 # Hz

  muse_state_publisher:
    enabled: false
    update_rate: 200 # Hz